[package]
name = "roblox-ui-classes"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
roblox-ui-http = { workspace = true }

anyhow = { workspace = true }
const_format = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
rbx_reflection = { workspace = true }
rbx_reflection_database = { workspace = true }
