[package]
name = "roblox-ui-reflection"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
roblox-ui-http = { workspace = true }

anyhow = { workspace = true }
const_format = { workspace = true }
quick-xml = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
